### ISSUE TITLE
Android: Allow to get more information about keyHandle and remove it

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxPush2#10]
Currently when user press on token application shows toast with push key id. It's not user friendly.
When user press on keyHanle in list application should should display KeyHandleFrame with information about keyHandle:
1) application
2) issuer
3) pairing date
4) last using date
5) last remote IP
6) etc.

Also application should allows to remove it

**Comment by willow9886** [comment]
+1

**Comment by NazarYavornytskyy** [comment]
All needed information is present in new build
