### ISSUE TITLE
Android plateforme 

### ISSUE THREAD

**Issue by houssine20** [GluuFederation/oxPush2#12]
i installed server gluu on ubuntu 14 and i compiled application android ,when i scan qr code i had  " hostename no assoicaite address ip " and no keyHandles , please help me

**Comment by mzico** [comment]
Hey @houssine20 : Please feel free to use our support portal (https://support.gluu.org ) for any kind of troubleshooting.

**Comment by houssine20** [comment]
Thank you Mr mzico
