### ISSUE TITLE
approve/decline button don't work after scaning

### ISSUE THREAD

**Issue by houssine20** [GluuFederation/oxPush2#13]
Hello ,

Thank you for your effort ,i installed server gluu 2.4.2 on ubuntu 14 and i compiled application android (apk debug) that's all , But after scanning QR code application and when i click approve button , display "unable to resolve host "ubuntu.gluu.info" address associated with hostname " can you help me step by step please.

Thank you very much. Regards,

**Comment by NazarYavornytskyy** [comment]
Currently I'm working on new version of oxPush2, new name is "Super Gluu", new version will have updated design and few improvements. Once I finished you can download code directly from Git and try to run. I'll inform you about any updates according this issue.

BR,
Nazar!

**Comment by houssine20** [comment]
Thank you Mr @NazarYavornytskyy , but can you give me link code "Super Gluu" please 
Regards,

**Comment by NazarYavornytskyy** [comment]
Yes, sure - https://github.com/GluuFederation/super-gluu

There are IOS and Android versions. IOS is done and waiting on publishing for Store, Android in progress - code not updated for long time, but I hope to finish this week and submit fresh updates.

**Comment by houssine20** [comment]
Thank you Mr NazarYavornytskyy But page 404 the message "this is not the web page you are looking for"

**Comment by NazarYavornytskyy** [comment]
I can open page - https://github.com/GluuFederation/super-gluu

Maybe you don't have privileges as this repo is PRIVATE, try later or ask Mike about it

**Comment by secureapp5544** [comment]
Can you help me please my friend

**Comment by NazarYavornytskyy** [comment]
I suppose to let's wait when I finished, currently Android version isn't working properly.

**Comment by secureapp5544** [comment]
About "super gluu", the part approve/decline work ?
and i don't have privileges as this repo

**Comment by NazarYavornytskyy** [comment]
For IOS version it's working well, for Android will be finished this week.

About privileges ask Mike or Will.

**Comment by houssine20** [comment]
Thank you very much my friend

**Comment by willow9886** [comment]
Just opened this issue to resolve this bug: https://github.com/GluuFederation/oxPush2/issues/14

**Comment by NazarYavornytskyy** [comment]
Approve/Deny buttons work for IOS and Android as well
