### ISSUE TITLE
Notification oxpush2

### ISSUE THREAD

**Issue by houssine20** [GluuFederation/oxPush2#15]
Hello , 

 How to configure and active notification , because i change in the file /etc/certs/oxpush2_creds.json to :

************************************
{
    "android":{
        "gcm":{
            "enabled":true,
            "api_key":"AIdoSyCkB33absOcZmXY_ic4Pqk82J-dBzn_rAc"
        }
    },
    "ios":{
        "apns":{
            "enabled":false,
            "p12_file_path":"/etc/certs/oxPush-NotificationCertificat.p12",
            "p12_password":"password",
            "production":false
        }
    }
}
************************************
but don't work .

Regards,

**Comment by NazarYavornytskyy** [comment]
So, as I remember oxPush2 already configured for receiving push notifications, isn't?

**Comment by houssine20** [comment]
Thank you Mr @NazarYavornytskyy for your response, I think no ,because default configuration in /etc/certs/oxpush2_creds.json is :

{
    "android":{
        "gcm":{
            "enabled":false,
            "api_key":""
        }
    },
    "ios":{
        "apns":{
            "enabled":false,
            "p12_file_path":"/etc/certs/oxPush-NotificationCertificat.p12",
            "p12_password":"password",
            "production":false
        }
    }
}

**Comment by yurem** [comment]
After changing this file you need to trigger oxPush2 script reload
The easy way is just stop/start tomcat
But it's also possible to do that without restart. You need to log into oxTrus, open custom script page an click update button at the bottom of this page. After maximum 30 seconds you should get notification in oxauth_scrpt.log about reload.

**Comment by houssine20** [comment]
Thank you , 

 About "authentication mode : authenticate"  after scan QR code is it normale? ,because he didn't send me message on android mobile (without Scan QR code)

**Comment by nynymike** [comment]
If you are using a one step authentication, then there would be no push. In  a two step, usually username/password is step one, and the push notificaiton is step 2.

**Comment by houssine20** [comment]
Thank you ,
  
  But in a two step is necessary to scan QR code before authenticate ? because always i scan qr before authenticate (after username/password) and he didn't send me message on android mobile like this for the example the Mr @nynymike.

![screenshot from 2016-05-11 20 28 38](https://cloud.githubusercontent.com/assets/7302125/15193795/890c1a62-17b7-11e6-81a3-754f032019a7.png)

Regards,

**Comment by yurem** [comment]
I understand what's wrong now. Thank you for screenshot. You activated oxpush but version which we offer to use is opxpush2. Moreover in CE 2.4.3 there is no this script: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/scripts.ldif
Latest version of this script is here:
https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations/oxpush2

But we include this script into CE 2.4.3 already

**Comment by nynymike** [comment]
The QR code is optional. If for some reason you don't get the push notification (and Apple/Google don't guanantee delivery), you can scan the code instead. I think I see your confusion though... perhaps we should make this an option (whether to display the code).

**Comment by houssine20** [comment]
Thank you Mr NazarYavornytskyy Mr nynymike Mr yurem ,is resolved .
the problem for me is Project number the google.

**Comment by NazarYavornytskyy** [comment]
I guess issue gone
