### ISSUE TITLE
Implement Decline action

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxPush2#3]
After scanning QR code and reviewing request info #2 user should be able do Declne action to send info to server to cancel authentication

**Comment by NazarYavornytskyy** [comment]
Decline action implemented for both platforms

**Comment by yurem** [comment]
Is application send request to server to cancel authentication request?

**Comment by NazarYavornytskyy** [comment]
No, currently app doesn't send authentication request to server in case Decline button clicked, could you please send me example of Cancel request, I'll add it for both applications?

**Comment by yurem** [comment]
Server side support this now. iOS application uses it now. We will add to Android application same functionality too.
