### ISSUE TITLE
Which minimum Android version application should support?

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxPush2#5]
According to this there are 3% of users which uses devices with Android 2.3.1.
I tried to run it on old mobile phone with 2.3.1 and it throws exception on startup. Probably we used methods IN GUI from more recent API.

We need to decide which minimum Android version we need to support.

**Comment by yurem** [comment]
http://developer.android.com/intl/ru/about/dashboards/index.html

**Comment by willow9886** [comment]
I would say Jelly Bean 4.x....
