### ISSUE TITLE
oxPush2 should send imfromation about device on enrollement

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxPush2#6]
In oxPush we gather next information about user mobile device:
					var deployment_entry = {
						device_uuid : req.body.device_uuid,
						device_type : req.body.device_type,
						device_name : req.body.device_name,
						os_name : req.body.os_name,
						os_version : req.body.os_version,
						approve_time : Date.now(),
						approve_ip : req.ip,
					};

**Comment by NazarYavornytskyy** [comment]
Seems works for both platforms

**Comment by yurem** [comment]
It's worked fine
