### ISSUE TITLE
Allow user use few login accounts in one step authentication

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxPush2#8]
We should allow user to use more than one device to log into his account.

**Comment by yurem** [comment]
We can use:
http://developer.android.com/intl/ru/training/articles/keystore.html

Android Keystore provider feature that was introduced in Android 4.3 (API level 18).
Hence after fixing this issue oxPush2 should work on Android devices >= 4.3

**Comment by NazarYavornytskyy** [comment]
I think the best way for this case is using only one keyHandle for one server to avoid saving redundant keys

**Comment by yurem** [comment]
I think subject of this issue is out of date.
New new one will be simpler. Going to change it

**Comment by NazarYavornytskyy** [comment]
IOS version already adopted for it, Android I think too
